USE [DB_A45479_EXPRESS]
GO

/****** Object:  Table [dbo].[EDUCATION_MAESTROS]    Script Date: 9/09/2019 10:51:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EDUCATION_MAESTROS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TOKEN] [varchar](100) NULL,
	[DPI] [varchar](20) NULL,
	[NOMBRES] [varchar](50) NULL,
	[APELLIDOS] [varchar](50) NULL,
	[PROFESION] [varchar](100) NULL,
	[NOTITULO] [varchar](25) NULL,
	[REGISTROESCALAFONARIO] [varchar](15) NULL,
	[IGSS] [float] NULL,
	[CICLO] [varchar](20) NULL,
	[GRADO] [varchar](20) NULL,
	[SECCION] [varchar](1) NULL,
	[TELEFONOS] [varchar](20) NULL,
	[CLAVE] [varchar](50) NULL,
 CONSTRAINT [PK_EDUCATION_MAESTROS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

